// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt53JhKdxY3kFR3lJEeDt8NAIQ8BVwtTE',
    appId: '1:773818088394:web:12f044dbdbb584d698ad33',
    messagingSenderId: '773818088394',
    projectId: 'meucontrolefinanceiroapp-4ea03',
    authDomain: 'meucontrolefinanceiroapp-4ea03.firebaseapp.com',
    storageBucket: 'meucontrolefinanceiroapp-4ea03.firebasestorage.app',
    measurementId: 'G-76BDM0Y57J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhbM_2VlyvkP6za0Icm7ZQsS-MjtVYmHo',
    appId: '1:773818088394:android:6ce7abdf32fd7b4c98ad33',
    messagingSenderId: '773818088394',
    projectId: 'meucontrolefinanceiroapp-4ea03',
    storageBucket: 'meucontrolefinanceiroapp-4ea03.firebasestorage.app',
  );
}
